# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#Test lane
platform :ios do
   desc "Runs all the tests"
   lane :test_application do
       begin
           alert_by_action("testing", git_branch, get_version_number(xcodeproj: "MVVM-C Project.xcodeproj"))
           test_lane()
       rescue => exception
           on_error(exception)
       end
   end
end

def test_lane
  run_tests(scheme: "MVVM-C Project",
            slack_url: "https://hooks.slack.com/services/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")
end

#Build Lane
lane :build_application do
       begin
           alert_by_action("building", git_branch, get_version_number(xcodeproj: "MVVM-C Project.xcodeproj"))
           build_lane()
       rescue => exception
           on_error(exception)
     end
end


#I have free apple developer account so I can't run build_app...
def build_lane
   #scan(scheme: "MVVM-C Project")
  #build_app(scheme: "MVVM-C Project")
build_app(
            configuration: "Debug",
            export_method: "development",
            scheme:"MVVM-C Project",
            skip_codesigning: true,
            skip_archive: true
        )
end

#Error
def on_error(exception)
slack(
   message: "Lane failed with exception : #{exception} version: #{get_version_number(xcodeproj: "MVVM-C Project.xcodeproj")}",
   success: false,
   slack_url: "https://hooks.slack.com/services/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")
end

//
def alert_by_action(actionType, branchName, version)
slack(
   message: "Started #{actionType} branchName: #{branchName}, version: #{version}",
   slack_url: "https://hooks.slack.com/services/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",
)
end 